### ISSUE TITLE
Add warehouse.

### ISSUE THREAD

**Issue by jakhangir-esanov** [wonderboy1w3/Recore#18]
- Add new feature that is warehouse. Your opertion should be worked for saved and chosed products.
_This task should be written by Mansurjon._ 
@misterpozitiv1607

**Comment by mansoorkhanmuydinovm** [comment]
> * Add new feature that is warehouse. Your opertion should be worked for saved and chosed products.
>   _This task should be written by Mansurjon._
>   @misterpozitiv1607

Xozircha domain qo'shdim marge qilish qoldi
